### ISSUE TITLE
Use websockets instead of polling

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1048]
Low priority. 

**Is your feature request related to a problem? Please describe.**

- The decision to use polling over WebSockets was a decision I took based on poor understanding of WebSockets.
- WebSockets will not use more resources, but should in fact use less.
- Polling requires server action and data transfer regardless of if the task is complete.
- WebSockets only transfer data when there is an update.

**Describe the solution you'd like**

- Currently Polling is used during project creation: QR code generation etc.
- We could change the response type to be WebSockets and subscribe to the creation event.
- This would likely require an update to the Nginx config to handle the `ws` protocol as well as http.

**Describe alternatives you've considered**

Webhooks, polling, websockets, pub sub.

**Additional context**

Part of the original decision was undoubtedly around the complexity of requiring the `ws` protocol via Nginx.

**TODO**
- [x] Remove `/projects/generate-log/` endpoint.
- [x] Remove code on frontend that polls via the endpoint.
- [ ] Use websockets for `/projects/generate-project-data` endpoint.
- [ ] Add code to frontend to keep connection alive via websocket.

**Comment by spwoodcock** [comment]
No longer required due to faster project creation. Could revisit this is required in the future.
