### ISSUE TITLE
Updates to mapper workflow based on in-person discussion

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1949]
### TODO

Mapper frontend (immediate):

- [x]  Remove the lock icon on mapper frontend when feature 'OPENED_IN_ODK' (only have the yellow colour).

React frontend

- [x]  Update text 'Select a task / feature for mapping' --> 'Click on a task to select a feature for mapping'.

- [x] - React frontend: add a button to refresh statuses on that map.
- [x] - If the React frontend project detail page is opened on a mobile device, automatically redirect to `/mapnow/{project_id}`
- [x]   - Related to this, remove the 'Start Mapping' button, as it's no longer needed.
- [x] - Move 'Basemaps' button from bottom left of map onto the left pane: 'Generate Basemaps'.
- [ ] - React frontend: add helper text when the page is loaded to 'Click on a task area', then have the text disappear when a task area is selected (not localStorage, but simply a conditional display: (if selectedTaskId) {showHelpText} else {doNotShowHelpText}
- [x] - Remove 'Start Mapping' in task popup, replace with 'Assign To Mapper'.

### TODO marking features as invalid / bad

- [x] We don't colour the task status if features are marked bad (hasIssues).
- [x] We call the ODK API to get submission details, filter by all features where `hasIssues` in ODK.
- [x] We convert he JavaRosa geom from ODK to a FeatureCollection of features that have issues.
- [x] Load and style those geoms as a layer on top of everything that flashes to the user 'fix me!'

**Comment by manjitapandey** [comment]
>  Move 'Basemaps' button from bottom left of map onto the left pane: 'Generate Basemaps'.
This will be addressed in #2037 

> React frontend: add helper text when the page is loaded to 'Click on a task area', then have the text disappear when a task area is selected (not localStorage, but simply a conditional display: (if selectedTaskId) {showHelpText} else {doNotShowHelpText}
@spwoodcock can you clarify, what do you mean by  (if selectedTaskId) {showHelpText} else {doNotShowHelpText}?

**Comment by manjitapandey** [comment]
> React frontend: add a button to refresh statuses on that map.

Does this refresh status button refreshes both tasks and feature's update or only refresh the status of feature?? As a project manager, i won't know the accurate progress if only features status is updated through syncing since i have to click on each tasks to see the update. I would rather refresh the page to get updates of both features and tasks.

**Comment by manjitapandey** [comment]
Currently, only the feature status are updated while syncing status and tasks status are not updated. 
Also in mobile view, sync status button is provided when the features are selected. We need to place it elsewhere to denote it updates both task level and feature level status.

**Comment by spwoodcock** [comment]
I think there is a misunderstanding here maybe?

The task statuses live update via electric SQL.

The feature statuses do too!

The problem for features is the fmtm db is not updated when the user submits via ODK, meaning we have to do this 'sync' part manually

**Comment by manjitapandey** [comment]
Re

**Comment by manjitapandey** [comment]
sorry my bad
