### ISSUE TITLE
Updates to manager workflow based on in-person discussion

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1950]
### TODO
To address immediately
- [x] Default don't show map on home page

- [x]  Use short description on home page project card
- [x]  Remove the debug console from dev (causing openlayers issue).

Project creation

- [x]  Upload Area --> Project Area
- [x]  ' Select one of the option to upload area' --> Upload project area
- [x]  'Click to reset' --> Reset
- [x]  When uploading AOI, also provide the area in km2 of the AOI
- [x]  'Select Survey Type' --> 'What are you surveying?'
- [x]  'Select a form' --> 'Upload XLSForm'
- [x]  'Map Features' --> 'Survey Data'

- For map feature upload:
  - Options:
    - 'Upload custom data' (default)
    - 'Download OSM data'
  - 'Generate Map Features' --> 'Fetch OSM Data'

Task splitting

- [x] 'Select an option to split the task' --> 'Select an option to split your project area'.
- [x] 'Divide on square' --> 'Split into squares'.
- [x] 'Choose area as task' --> 'Use uploaded AOI as task areas'.
- [x] Clicking on a toggle / option should change the text on the left to describe the action.

- 'Task splitting algorithm' --> 'Task splitting algorithm'
  - Number of buildings
  - Number of enumerators
  - Optimise on time taken (including walking and mapping time).

- [x] - After splitting, remove additional feature count, move to section with the additional feature upload

**Comment by NSUWAL123** [comment]
@Anuj-Gupta4, in `/projects/summaries` endpoint, replace description with short description
