### ISSUE TITLE
Enable all submitted organisations on production instance

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1951]
**Todo**

- [x] Approve organisations that have been created by people on prod.
- [ ] Set the default ODK creds as the HOT instance.
- [x] Test creating a project as a different org than HOTOSM.

**Comment by manjitapandey** [comment]
1st and third point is already done and is functional.

**Comment by spwoodcock** [comment]
I will finalise this now by adding ODK Central users for each requested org 👍 

Note that we previously had a bug where the `created_by` requesting user was not recorded!

![Image](https://github.com/user-attachments/assets/363f7a88-6ef5-4d01-9ebe-f53e10fd702b)

So we don't know who requested creation of these orgs, to assign them org admin. We might have to find out via informal means such as asking in the slack community.

**Comment by spwoodcock** [comment]
We have no easy way of knowing who created the org (org creation shouldn't have been enabled until we implemented it properly, but we are where we are now 😅 ).

It's not a huge deal, as long as people know how to contact us (slack channel).

We can either:
- Wait for the org creator to contact us and we update their permissions
- Delete the orgs without an admin, to allow them to re-create it.

**Comment by spwoodcock** [comment]
Anyways, this is complete now.

As of now, we have these orgs approved:

![Image](https://github.com/user-attachments/assets/3c05b4e0-82a1-4bd9-a25a-18c1dbe5b4ed)

**Comment by spwoodcock** [comment]
Good idea, thank you!

Yep, we can make them org managers if we know the OSM user id 👍

**Comment by manjitapandey** [comment]
![Image](https://github.com/user-attachments/assets/04074ac9-af94-401c-a2e6-f2082858b757)
